blog_rest_api/config/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework_swagger.views import get_swagger_view

from post_service import views

schema_view = get_swagger_view(title='REST API TEST')

# config 의 urls 에서 namespace 를 사용하려면 app_name 지정 필수
urlpatterns = [
    path('admin/', admin.site.urls),
	path('board/', include('post_service.urls', namespace='post_service')),
	path('user/', include('user_manager.urls', namespace='user_manager')),
	
	path('rest-swagger/', schema_view),
	path('rest-api/', include('rest_framework.urls')),
	path('api/post/', views.Post_api.as_view()),
]

blog_rest_api/post_service/urls.py
from django.urls import path, include

from . import views

# config 의 urls 에서 namespace 를 사용하려면 app_name 지정 필수
app_name = 'post_service'
urlpatterns = [
	path('', views.PostListView.as_view(), name='index'),
]

blog_rest_api/user_manager/urls.py
from django.urls import path, include

from . import views

# config 의 urls 에서 namespace 를 사용하려면 app_name 지정 필수
app_name = 'user_manager'
urlpatterns = [
	path('login/', views.login, name='login'),
	path('login/validate/', views.login_validate, name='login_validate'),
	path('join/', views.join_page, name='join'),
]

blog_rest_api/post_service/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
	title = models.CharField(max_length=1024)
	body = models.CharField(max_length=4096)
	author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
	regdate = models.DateTimeField(auto_created=True, auto_now_add=True)
	# 시간이 자동으로 생성되고 / 현재 시간이 자동으로 기록되는

blog_rest_api/user_manager/models.py
from django.db import models

# Create your models here.

blog_rest_api/user_manager/forms.py
from django import forms

class LoginForm(forms.Form):
	id = forms.CharField(label='ID', max_length=12)
	# widget 증 forms.PasswordInput 은 패스워드 입력 시 문자가 보이지 않도록 처리
	password = forms.CharField(label='PASSWORD', max_length=12, widget=forms.PasswordInput)
	
class JoinForm(forms.Form):
	#  ID는 최소 4자 이상, 12사 이하 / 비밀번호는 최소 6자 이상 12자 이하
	id = forms.CharField(label='ID', min_length=4, max_length=12, required=True)
	password = forms.CharField(label='PASSWORD', min_length=6, max_length=12, required=True, 
								widget=forms.PasswordInput)
	password_check = forms.CharField(label='PASSWORD(input again)', min_length=6, 
										max_length=12, required=True, widget=forms.PasswordInput)

blog_rest_api/post_service/views.py
from django.shortcuts import render
from django.views.generic import ListView
#from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from rest_framework import serializers, mixins, viewsets
from rest_framework.generics import GenericAPIView

from .models import Post
from .serializers import PostSerializer

class PostListView(ListView):
	model = Post
	template_name = 'post_list.html'
	paginate_by = 3
	
	def get_context_data(self, **kwargs):
		context = super(PostListView, self).get_context_data(**kwargs)
		paginator = context['paginator']
		page_numbers_range = 5 # 인덱스 숫자 수 표시제한
		max_index = len(paginator.page_range)
		
		page = self.request.GET.get('page')
		current_page = int(page) if page else 1 # page 가 0일 경우, 1로 할당
		
		start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
		end_index = start_index + page_numbers_range
		# 끝 인덱스는 항상 페이지의 max_index에 맞춤
		if end_index >= max_index:
			end_index = max_index
			
		page_range = paginator.page_range[start_index:end_index]
		context['page_range'] = page_range
		return context		

'''
def post_list(request):
	page_data = Paginator(Post.objects.all(), 3)
	page = request.GET.get('page')
	
	# /board/ 페이지 접속 시 page 변수에 none이 할당되어 int로 변환 불가한 오류뜸
	# 아래처럼 page가 none일 경우 첫페이지로 볼 수 있도록 if 처리
	if page is None:
		page = 1
	
	try:
		posts = page_data.page(page)
	# 페이지 첫 접속 시 page가 int 형이 아니므로 except 처리함
	except PageNotAnInteger:
		posts = page_data.page(1)
	except EmptyPage:
		posts = page_data.page(page_data.num_pages)
		# page_data.num_pages 는 전체 페이지 수를 나타냄

	# range 함수로 는 전체 페이지 수에서 범위를 리스트로 만듬
	# int 는 total_page가 range 함수로 적용되었기 때문에 템플릿에서 함께 연산되려면 int 형으로 변경 필요함
	context = {'post_list':posts, 'current_page':int(page), 'total_page':range(1, page_data.num_pages + 1)}
	
	return render(request, 'post_list.html', context)
'''

class Post_api(GenericAPIView, mixins.ListModelMixin):
	queryset = Post.objects.all()
	serializer_class = PostSerializer
	
	def get(self, request, *args, **kwargs):
		return self.list(request, *args, **kwargs)

blog_rest_api/user_manager/views.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponse
from django.contrib import auth
from django.contrib.auth.models import User

from .forms import LoginForm, JoinForm

# Create your views here.

def login(request):
	context = {'login_form':LoginForm}
	return render(request, 'login_form.html', context)
	
def login_validate(request):
	login_form_data = LoginForm(request.POST)
	
	if login_form_data.is_valid():
		# authenticate() 함수는 username과 password 등, 여러가지 파라메터를 통하여 인증 과정을 수행
		# django.contrib.auth.models 에 포함된 User 모델의 데이터로 검증을 수행
		# username 이나 password에 login_form_data 인스턴스 내용들 할당 시, cleaned_data(사전형) 로 id 와 password 지정 필요
		user = auth.authenticate(username=login_form_data.cleaned_data['id'], 
									password=login_form_data.cleaned_data['password'])
		
		if user is not None:
			# 계정 활성화 여부 체크
			if user.is_active:
				auth.login(request, user)
				
				return redirect('post_service:index')
		else:
			return HttpResponse('사용자가 없거나 비밀번호를 잘못 입력하였습니다.')
	else:
		return HttpResponse('로그인 폼이 비정상 입니다.')
	
	return HttpResponse('알 수 없는 오류 입니다.')
	
def join_page(request):
	# POST로 넘어온 데이터는 회원 가입 로직으로 처리
	if request.method == 'POST':
		form_data = JoinForm(request.POST)
		
		if form_data.is_valid():
			username = form_data.cleaned_data['id']
			password = form_data.cleaned_data['password']
			password_check = form_data.cleaned_data['password_check']
			# 입력한 비밀번호와 재확인 내용이 같은지 확인
			if password == password_check:
				User.objects.create_user(username=username, password=password)			
				return redirect('user_manager:login')
			else:
				return HttpResponse('비밀번호와 비밀번호 확인의 내용이 다릅니다.')
	# POST 이외의 메소드로 넘어오면 빈 form 처리
	else:
		form_data = JoinForm()

	context = {'join_form':form_data}
	return render(request, 'join_page.html', context)

blog_rest_api/post_service/templates/login_form.html
<!DOCTYPE html>
<html>
<head>
	<title>
		Login form
	</title>
</head>
<body>
	<form action="{% url 'post_service:login_validate' %}" method="POST">
		{% csrf_token %}
		{{ login_form }}
		<input type="submit" value="로그인">
	</form>
</body>
</html>

blog_rest_api/post_service/templates/post_list.html
<!DOCTYPE html>
<html>
<head lang="en">
	<meta charse="UTF-8">
	<title></title>
	<style>
		table {
			width: 100%;
		}
		table, thead, tbody, tr {
			border: 1px solid #ececec;
			border-collapse: collapse;
			text-align: center;
		}
		thead>tr>th {
			padding: 4px;
			background-color: beige;
		}
		tbody>tr>td{
			padding: 6px;
		}
		div#paging_area {
			padding: 6px;
			text-align: center;
			font-size: 14px;
		}
	</style>
</head>
<body>
	<table>
		<colgroup>
			<col span="1" width="12%">
			<col span="1" width="50%">
			<col span="1" width="18%">
			<col span="1" width="20%">
		</colgroup>
		
		<thead>
			<tr>
				<th>번호</th>
				<th>제목</th>
				<th>작성자</th>
				<th>날짜</th>
			</tr>
		</thead>
		
		<tbody>
		{% for item in object_list %}
			<tr>
				<td>{{ item.pk }}</td>
				<td>{{ item.title }}</td>
				<td>{{ item.author }}</td>
				<td>{{ item.regdate }}</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
	
	<div id="paging_area">
		{% if is_paginated %}
		
			{% if page_obj.has_previous %}
				<a href="?page={{ page_obj.previous_page_number }}">Prev</a>
			{% endif %}
			
			{% for page in page_range %}
				<a {% if page != page_obj.number %} href="?page={{ page }}" {% endif %}
					<span {% if page == page_obj.number %} style="font-weight:bold" {% endif %}>
				{{ page }}
			{% endfor %}
			
			{% if page_obj.has_next %}
				<a href="?page={{ page_obj.next_page_number }}">Next</a>
			{% endif %}	
			
		{% endif %}
	</div>
</body>
</html>

blog_rest_api/user_manager/templates/join_page.html
<!DOCTYPE html>
<html>
<head>
	<title>회원가입</title>
	<style>
		form {
			display: block;
			padding: 12px;
		}
		form div.form_wrapper {
			margin-bottom: 12px;
			box-shadow: 2px 2px 4px #000;
			border: 1px solid #FFF;
		}
		form div.form_wrapper div.input_form {
			display: flex;
			margin: 12px;
			align-items: center;
		}
		form div.form_wrapper div.input_form label {
			margin-right: 12px;
			min-width: 200px;
		}
		form div.form_wrapper div.input_form input {
			flex: 1;
		}
		form input[type=submit] {
			width: 100%;
			background-color: #ececec;
			padding: 12px;
		}
	</style>
</head>
<body>
	<form action="" method="POST">
		{% csrf_token %}
		<div class="form_wrapper">
			<div class="input_form">
				<label for="{{ join_form.id.id_for_label }}">{{ join_form.id.label }}</label>
				{{ join_form.id }}
			</div>
			<div class="input_form">
				<label for="{{ join_form.password.password_for_label }}">{{ join_form.password.label }}</label>
				{{ join_form.password }}
			</div>			
			<div class="input_form">
				<label for="{{ join_form.id.password_check_for_label }}">{{ join_form.password_check.label }}</label>
				{{ join_form.password_check }}
			</div>
		</div>
		<input type="submit" value="회원가입">
	</form>
</body>
</html>

blog_rest_api/user_manager/templates/login_form.html
<!DOCTYPE html>
<html>
<head>
	<title>회원가입</title>
	<style>
		form {
			display: block;
			padding: 12px;
		}
		form div.form_wrapper {
			margin-bottom: 12px;
			box-shadow: 2px 2px 4px #000;
			border: 1px solid #FFF;
		}
		form div.form_wrapper div.input_form {
			display: flex;
			margin: 12px;
			align-items: center;
		}
		form div.form_wrapper div.input_form label {
			margin-right: 12px;
			min-width: 200px;
		}
		form div.form_wrapper div.input_form input {
			flex: 1;
		}
		form input[type=submit] {
			width: 100%;
			background-color: #ececec;
			padding: 12px;
		}
	</style>
</head>
<body>
	<form action="{% url 'user_manager:login_validate' %}" method="POST">
		{% csrf_token %}
		<div class="form_wrapper">
			<div class="input_form">
				<label for="{{ login_form.id.id_for_label }}">{{ login_form.id.label }}</label>
				{{ login_form.id }}
			</div>
			<div class="input_form">
				<label for="{{ login_form.password.password_for_label }}">{{ login_form.password.label }}</label>
				{{ login_form.password }}
			</div>			
		</div>
		<input type="submit" value="로그인">
	</form>
</body>
</html>